# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(email: 'kaherreras@unal.edu.co', role: 'Admin', name: 'Kevin Andrey Herrera Silva', password: '123456', password_confirmation: '123456')
User.create(email: 'viviana.arango1505@gmail.com', role: 'Admin', name: 'Viviana Arango Grisales', password: '123456', password_confirmation: '123456')
User.create(email: 'admin@ldws.com', role: 'Admin', name: 'Administrador LDWS', password: '123456', password_confirmation: '123456')

Port.create(name: "RJ45-1", speed: "1")
Port.create(name: "SFP", speed: "1")
Port.create(name: "SFP+", speed: "10")
Port.create(name: "QSFP", speed: "10")
Port.create(name: "QSFP+", speed: "40")
Port.create(name: "RJ45-10", speed: "10")

Ethernet.create(name: "10GBASE-SR", speed: "10", distance: "33")
Ethernet.create(name: "10GBASE-LX4", speed: "10", distance: "300")
Ethernet.create(name: "10GBASE-SR", speed: "10", distance: "82")
Ethernet.create(name: "10GBASE-LX4", speed: "10", distance: "300")
Ethernet.create(name: "100GBASE-SR10", speed: "100", distance: "100")
Ethernet.create(name: "40GBASE-SR4", speed: "40", distance: "100")
Ethernet.create(name: "10GBASE-SR", speed: "10", distance: "300")
Ethernet.create(name: "10GBASE-LX4", speed: "10", distance: "300")
Ethernet.create(name: "100GBASE-SR10", speed: "100", distance: "150")
Ethernet.create(name: "40GBASE-SR4", speed: "40", distance: "150")
Ethernet.create(name: "10GBASE-SR", speed: "10", distance: "490")
Ethernet.create(name: "10GBASE-LX4", speed: "10", distance: "300")
Ethernet.create(name: "1000BASE-T", speed: "1", distance: "100")
Ethernet.create(name: "10GBASE-T", speed: "10", distance: "50")

Connector.create(name: "SC", price: "2")
Connector.create(name: "LC", price: "2")
Connector.create(name: "RJ45", price: "1")
Connector.create(name: "Transceiver SFP", price: "3")
Connector.create(name: "Transceiver SFP+", price: "3")
Connector.create(name: "Transceiver QSFP", price: "4")
Connector.create(name: "Transceiver QSFP+", price: "4")

Category.create(name: "OM1", price: "5")
Category.create(name: "OM2", price: "10")
Category.create(name: "OM3", price: "15")
Category.create(name: "OM4", price: "20")
Category.create(name: "CAT6", price: "2")
Category.create(name: "CAT6A", price: "3")

Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "1", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "2", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "3", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "4", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "5", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "6", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "7", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "8", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "9", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "10", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "11", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "1", ethernet_id: "12", category_id: "4")

Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "1", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "2", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "3", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "4", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "5", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "6", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "7", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "8", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "9", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "10", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "11", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "2", ethernet_id: "12", category_id: "4")

Cable.create(name: "Par Trenzado", ctype: "UTP", structure: "UTP", connector_id: "3", ethernet_id: "13", category_id: "5")
Cable.create(name: "Par Trenzado", ctype: "UTP", structure: "UTP", connector_id: "3", ethernet_id: "14", category_id: "6")
Cable.create(name: "Par Trenzado", ctype: "UTP", structure: "FTP", connector_id: "3", ethernet_id: "13", category_id: "5")
Cable.create(name: "Par Trenzado", ctype: "UTP", structure: "FTP", connector_id: "3", ethernet_id: "14", category_id: "6")
Cable.create(name: "Par Trenzado", ctype: "UTP", structure: "STP", connector_id: "3", ethernet_id: "13", category_id: "5")
Cable.create(name: "Par Trenzado", ctype: "UTP", structure: "STP", connector_id: "3", ethernet_id: "14", category_id: "6")

Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "1", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "2", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "3", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "4", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "5", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "6", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "7", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "8", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "9", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "10", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "11", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "4", ethernet_id: "12", category_id: "4")

Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "1", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "2", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "3", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "4", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "5", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "6", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "7", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "8", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "9", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "10", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "11", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "5", ethernet_id: "12", category_id: "4")

Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "1", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "2", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "3", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "4", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "5", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "6", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "7", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "8", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "9", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "10", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "11", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "6", ethernet_id: "12", category_id: "4")

Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "1", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "2", category_id: "1")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "3", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "4", category_id: "2")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "5", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "6", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "7", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "8", category_id: "3")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "9", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "10", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "11", category_id: "4")
Cable.create(name: "Fibra Optica", ctype: "Multimodo", structure: "Tight-Buffer", connector_id: "7", ethernet_id: "12", category_id: "4")

Switch.create(name: "Cisco", reference: "2407", price: "100")
Switch.create(name: "Huawei", reference: "4771", price: "500")

aux=Port.count
while aux>0
    TheSwitch.create(switches_id: 1, ports_id: aux, numberports: 5)
    TheSwitch.create(switches_id: 2, ports_id: aux, numberports: 10)
    aux-=1
end
puts "Defecto Ok"